In [1]:
import pandas as pd

Eversource = pd.read_csv('Eversource.csv')
Eversource.head()

,TOWN,ZIPCODE,Average Customer Duration ( Hours),Total Duration Hours,# Events Affecting Town/Zipcode,Customers Served,Outages Per Customer,Events/Customer Above Average IND,Duration Above Average
0,ABINGTON,6230,24,31729.4,128,104,1.231,BelowAverage,BelowAverage
1,AMSTON,6231,20,166846.9,222,840,0.264,BelowAverage,BelowAverage
2,ANDOVER,6232,24,234042.6,299,1429,0.209,BelowAverage,BelowAverage
3,ASHFORD,6278,21,490057.4,455,2204,0.206,BelowAverage,BelowAverage
4,AVON,6001,21,1020814.8,584,8756,0.067,BelowAverage,BelowAverage

In [2]:
from geoid import acs

In [3]:
ct = pd.read_csv('ct_cbgs.csv')
ct.head()

,Unnamed: 0,GEOID10,Housing burden (percent),Total population,Median household income (% of state median household income),Current asthma among adults aged >=18 years,Coronary heart disease among adults aged >=18 years,Cancer (excluding skin cancer) among adults aged >=18 years,Current lack of health insurance among adults aged 18-64 years,Diagnosed diabetes among adults aged >=18 years,...,Score K (communities),county,tract,bg,zcta5,cntyname,zipname,pop2k,afact,cbgid
0,0,90010101011,0.224719,1058.0,2.370761,8.5,6.7,9.9,5.9,8.6,...,False,9001,101.01,1,6831,Fairfield CT,GREENWICH,779,1.000,90010101011
1,1,90010101012,0.224719,600.0,1.560464,8.5,6.7,9.9,5.9,8.6,...,False,9001,101.01,2,6831,Fairfield CT,GREENWICH,785,1.000,90010101012
2,2,90010101013,0.224719,1221.0,3.187000,8.5,6.7,9.9,5.9,8.6,...,False,9001,101.01,3,6831,Fairfield CT,GREENWICH,1494,1.000,90010101013
3,3,90010101014,0.224719,1393.0,1.659222,8.5,6.7,9.9,5.9,8.6,...,False,9001,101.01,4,6831,Fairfield CT,GREENWICH,1603,1.000,90010101014
4,4,90010101021,0.103586,1358.0,3.187000,8.0,5.0,8.6,4.5,7.0,...,False,9001,101.02,1,6830,Fairfield CT,BYRAM,820,0.617,90010101021

In [4]:
ct = ct.drop(['Current asthma among adults aged >=18 years', 'Coronary heart disease among adults aged >=18 years', 'Cancer (excluding skin cancer) among adults aged >=18 years', 'Diagnosed diabetes among adults aged >=18 years', 'Physical health not good for >=14 days among adults aged >=18 years', ], axis = 1)

In [5]:
ct.head()

,Unnamed: 0,GEOID10,Housing burden (percent),Total population,Median household income (% of state median household income),Current lack of health insurance among adults aged 18-64 years,Percent of individuals < 100% Federal Poverty Line,Percent of individuals < 150% Federal Poverty Line,Percent of individuals < 200% Federal Poverty Line,Area Median Income (State or metropolitan),...,Score K (communities),county,tract,bg,zcta5,cntyname,zipname,pop2k,afact,cbgid
0,0,90010101011,0.224719,1058.0,2.370761,5.9,0.072154,0.237805,0.293699,95645.0,...,False,9001,101.01,1,6831,Fairfield CT,GREENWICH,779,1.000,90010101011
1,1,90010101012,0.224719,600.0,1.560464,5.9,0.000000,0.030837,0.063142,95645.0,...,False,9001,101.01,2,6831,Fairfield CT,GREENWICH,785,1.000,90010101012
2,2,90010101013,0.224719,1221.0,3.187000,5.9,0.050263,0.051013,0.051013,95645.0,...,False,9001,101.01,3,6831,Fairfield CT,GREENWICH,1494,1.000,90010101013
3,3,90010101014,0.224719,1393.0,1.659222,5.9,0.031603,0.041761,0.041761,95645.0,...,False,9001,101.01,4,6831,Fairfield CT,GREENWICH,1603,1.000,90010101014
4,4,90010101021,0.103586,1358.0,3.187000,4.5,0.014239,0.014239,0.069903,95645.0,...,False,9001,101.02,1,6830,Fairfield CT,BYRAM,820,0.617,90010101021

In [6]:
ct_refined = ct[['GEOID10','Median household income (% of state median household income)', 'Area Median Income (State or metropolitan)', 'zipname']].copy()
ct_refined.head()

,GEOID10,Median household income (% of state median household income),Area Median Income (State or metropolitan),zipname
0,90010101011,2.370761,95645.0,GREENWICH
1,90010101012,1.560464,95645.0,GREENWICH
2,90010101013,3.187000,95645.0,GREENWICH
3,90010101014,1.659222,95645.0,GREENWICH
4,90010101021,3.187000,95645.0,BYRAM

In [18]:
ct_merged = pd.read_csv('merged_data.csv')
ct_refined = ct_merged[['Median household income (% of state median household income)', 'Area Median Income (State or metropolitan)', 'zipname_y', 'ZIPCODE', 'Housing burden (percent)', 'Energy burden', 'Energy burden (percentile)', 'Individuals over 64 years old', 'Physical health not good for >=14 days among adults aged >=18 years', 'FEMA Risk Index Expected Annual Loss Score', 'Housing + Transportation Costs % Income for the Regional Typical Household (percentile)', 'Percent individuals age 25 or over with less than high school degree (percentile)', 'Persistent Poverty Census Tract', 'Percent of individuals < 200% Federal Poverty Line (percentile)', 'Life expectancy (years)']].copy()
ct_refined.head()

,Median household income (% of state median household income),Area Median Income (State or metropolitan),zipname_y,ZIPCODE,Housing burden (percent),Energy burden,Energy burden (percentile),Individuals over 64 years old,Physical health not good for >=14 days among adults aged >=18 years,FEMA Risk Index Expected Annual Loss Score,Housing + Transportation Costs % Income for the Regional Typical Household (percentile),Percent individuals age 25 or over with less than high school degree (percentile),Persistent Poverty Census Tract,Percent of individuals < 200% Federal Poverty Line (percentile),Life expectancy (years)
0,2.370761,95645.0,GREENWICH,6831,0.224719,0.02,0.199716,0.275992,10.4,17.342298,0.936984,0.373408,False,0.495065,81.0
1,1.560464,95645.0,GREENWICH,6831,0.224719,0.02,0.199716,0.175000,10.4,17.342298,0.930205,0.278633,False,0.072679,81.0
2,3.187000,95645.0,GREENWICH,6831,0.224719,0.02,0.199716,0.200655,10.4,17.342298,0.856143,0.141046,False,0.053861,81.0
3,1.659222,95645.0,GREENWICH,6831,0.224719,0.02,0.199716,0.323044,10.4,17.342298,0.805288,0.349333,False,0.040672,81.0
4,3.187000,95645.0,GREENWICH,6831,0.103586,0.02,0.199716,0.192931,8.1,15.736806,0.943163,0.130473,False,0.083604,85.5

In [19]:
ct_refined = ct_refined.groupby('ZIPCODE').mean()

In [20]:
Final_data = pd.merge(ct_refined, Eversource, on='ZIPCODE')

In [22]:
print(Final_data)

     ZIPCODE  Median household income (% of state median household income)  \
0       6001                                           1.826267
1       6002                                           1.015136
2       6010                                           0.900913
3       6013                                                NaN
4       6016                                           1.183614
..       ...                                                ...
259     6902                                           1.312952
260     6903                                           2.461202
261     6905                                           1.631253
262     6906                                           1.224287
263     6907                                           1.521947

     Area Median Income (State or metropolitan)  Housing burden (percent)  \
0                                       77769.0                  0.157547
1                                       77769.0                  0.298781
2                                       77769.0                  0.291703
3                                           NaN                       NaN
4                                       77769.0                  0.236299
..                                          ...                       ...
259                                     95645.0                  0.340288
260                                     95645.0                  0.148039
261                                     95645.0                  0.230479
262                                     95645.0                  0.391075
263                                     95645.0                  0.283370

     Energy burden  Energy burden (percentile)  Individuals over 64 years old  \
0         0.022000                    0.252437                       0.196476
1         0.034545                    0.570185                       0.215335
2         0.041250                    0.692750                       0.152961
3              NaN                         NaN                            NaN
4         0.034000                    0.557362                       0.183749
..             ...                         ...                            ...
259       0.025156                    0.331629                       0.133888
260       0.020000                    0.199716                       0.205858
261       0.020571                    0.214779                       0.144297
262       0.022500                    0.265617                       0.140883
263       0.023333                    0.287584                       0.127922

     Physical health not good for >=14 days among adults aged >=18 years  \
0                                             8.300000
1                                            11.645455
2                                            12.218750
3                                                  NaN
4                                            10.380000
..                                                 ...
259                                          10.123438
260                                           8.400000
261                                           8.580000
262                                          10.331250
263                                           9.700000

     FEMA Risk Index Expected Annual Loss Score  \
0                                     18.623516
1                                     20.480549
2                                     24.535966
3                                           NaN
4                                     13.538465
..                                          ...
259                                   36.437038
260                                   23.650915
261                                   36.601474
262                                   37.136625
263                                   33.644110

     Housing + Transportation Costs % Income for the Regional Typical Household (percentile)  \
0                                             0.719441
1                                             0.314730
2                                             0.260891
3                                                  NaN
4                                             0.487276
..                                                 ...
259                                           0.350692
260                                           0.854561
261                                           0.518493
262                                           0.294533
263                                           0.574272

     ...  Percent of individuals < 200% Federal Poverty Line (percentile)  \
0    ...                                           0.128791
1    ...                                           0.276419
2    ...                                           0.408359
3    ...                                                NaN
4    ...                                           0.191957
..   ...                                                ...
259  ...                                           0.344369
260  ...                                           0.057091
261  ...                                           0.167506
262  ...                                           0.376000
263  ...                                           0.191010

     Life expectancy (years)         TOWN Average Customer Duration ( Hours)  \
0                  82.860000         AVON                                 21
1                  79.818182   BLOOMFIELD                                 18
2                  79.371875      BRISTOL                                 23
3                        NaN   BURLINGTON                                 24
4                  79.540000  BROAD BROOK                                 37
..                       ...          ...                                ...
259                81.518750     STAMFORD                                 44
260                85.200000     STAMFORD                                 46
261                82.620000     STAMFORD                                 32
262                81.268750     STAMFORD                                 29
263                81.700000     STAMFORD                                 32

     Total Duration Hours  # Events Affecting Town/Zipcode  Customers Served  \
0               1020814.8                              584              8756
1                579255.5                              577             10708
2               1407252.9                              660             29940
3                408591.7                              248              3921
4                307871.1                              163              3042
..                    ...                              ...               ...
259             1320958.7                              788             30931
260             1504628.2                             1480              5472
261              579299.8                              485              9598
262              247825.0                              156              4346
263              246211.5                              194              4279

     Outages Per Customer  Events/Customer Above Average IND  \
0                   0.067                       BelowAverage
1                   0.054                       BelowAverage
2                   0.022                       BelowAverage
3                   0.063                       BelowAverage
4                   0.054                       BelowAverage
..                    ...                                ...
259                 0.025                       BelowAverage
260                 0.270                       BelowAverage
261                 0.051                       BelowAverage
262                 0.036                       BelowAverage
263                 0.045                       BelowAverage

    Duration Above Average
0             BelowAverage
1             BelowAverage
2             BelowAverage
3             BelowAverage
4             BelowAverage
..                     ...
259           BelowAverage
260           BelowAverage
261           BelowAverage
262           BelowAverage
263           BelowAverage

[264 rows x 21 columns]

In [ ]:
Final_data.